//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGrowHub.Maui.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartGrowHub.Maui.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        internal static string LogInToYourAccount {
            get {
                return ResourceManager.GetString("LogInToYourAccount", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string ForgotThePassword {
            get {
                return ResourceManager.GetString("ForgotThePassword", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        internal static string CreateYourNewAccount {
            get {
                return ResourceManager.GetString("CreateYourNewAccount", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }
        
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string YourPlants {
            get {
                return ResourceManager.GetString("YourPlants", resourceCulture);
            }
        }
        
        internal static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string FailedLogInYourAccount {
            get {
                return ResourceManager.GetString("FailedLogInYourAccount", resourceCulture);
            }
        }
        
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        internal static string LogInToYourAccountAgain {
            get {
                return ResourceManager.GetString("LogInToYourAccountAgain", resourceCulture);
            }
        }
        
        internal static string FailedToRefreshPage {
            get {
                return ResourceManager.GetString("FailedToRefreshPage", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string EmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("EmailOrPhoneNumber", resourceCulture);
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        internal static string CodeHasBeenSentTo {
            get {
                return ResourceManager.GetString("CodeHasBeenSentTo", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string HaveYouEnteredIncorrectData {
            get {
                return ResourceManager.GetString("HaveYouEnteredIncorrectData", resourceCulture);
            }
        }
        
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        internal static string Seedling {
            get {
                return ResourceManager.GetString("Seedling", resourceCulture);
            }
        }
        
        internal static string Vegetative {
            get {
                return ResourceManager.GetString("Vegetative", resourceCulture);
            }
        }
        
        internal static string Flowering {
            get {
                return ResourceManager.GetString("Flowering", resourceCulture);
            }
        }
        
        internal static string MyPlan {
            get {
                return ResourceManager.GetString("MyPlan", resourceCulture);
            }
        }
        
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        internal static string Inside {
            get {
                return ResourceManager.GetString("Inside", resourceCulture);
            }
        }
        
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        internal static string Vpd {
            get {
                return ResourceManager.GetString("Vpd", resourceCulture);
            }
        }
        
        internal static string TemperatureShort {
            get {
                return ResourceManager.GetString("TemperatureShort", resourceCulture);
            }
        }
        
        internal static string kPa {
            get {
                return ResourceManager.GetString("kPa", resourceCulture);
            }
        }
        
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        internal static string ManualProgram {
            get {
                return ResourceManager.GetString("ManualProgram", resourceCulture);
            }
        }
        
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        internal static string TurnedOffShort {
            get {
                return ResourceManager.GetString("TurnedOffShort", resourceCulture);
            }
        }
        
        internal static string DailySchedule {
            get {
                return ResourceManager.GetString("DailySchedule", resourceCulture);
            }
        }
        
        internal static string WeeklySchedule {
            get {
                return ResourceManager.GetString("WeeklySchedule", resourceCulture);
            }
        }
        
        internal static string DayLight {
            get {
                return ResourceManager.GetString("DayLight", resourceCulture);
            }
        }
        
        internal static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        internal static string Heater {
            get {
                return ResourceManager.GetString("Heater", resourceCulture);
            }
        }
        
        internal static string TurnedOnShort {
            get {
                return ResourceManager.GetString("TurnedOnShort", resourceCulture);
            }
        }
        
        internal static string DisabledSchedule {
            get {
                return ResourceManager.GetString("DisabledSchedule", resourceCulture);
            }
        }
        
        internal static string EnabledSchedule {
            get {
                return ResourceManager.GetString("EnabledSchedule", resourceCulture);
            }
        }
        
        internal static string SensorAirTemperatureShort {
            get {
                return ResourceManager.GetString("SensorAirTemperatureShort", resourceCulture);
            }
        }
        
        internal static string SensorAirPressureShort {
            get {
                return ResourceManager.GetString("SensorAirPressureShort", resourceCulture);
            }
        }
        
        internal static string SensorAirHumidityShort {
            get {
                return ResourceManager.GetString("SensorAirHumidityShort", resourceCulture);
            }
        }
        
        internal static string SensorPlantHeightShort {
            get {
                return ResourceManager.GetString("SensorPlantHeightShort", resourceCulture);
            }
        }
        
        internal static string SensorSoilMoistureShort {
            get {
                return ResourceManager.GetString("SensorSoilMoistureShort", resourceCulture);
            }
        }
        
        internal static string SensorSoilTemperatureShort {
            get {
                return ResourceManager.GetString("SensorSoilTemperatureShort", resourceCulture);
            }
        }
        
        internal static string SensorIlluminationShort {
            get {
                return ResourceManager.GetString("SensorIlluminationShort", resourceCulture);
            }
        }
        
        internal static string SensorRandomNumberShort {
            get {
                return ResourceManager.GetString("SensorRandomNumberShort", resourceCulture);
            }
        }
        
        internal static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string NoScheduleEntries {
            get {
                return ResourceManager.GetString("NoScheduleEntries", resourceCulture);
            }
        }
        
        internal static string AddScheduleEntry {
            get {
                return ResourceManager.GetString("AddScheduleEntry", resourceCulture);
            }
        }
        
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        internal static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        internal static string EndDay {
            get {
                return ResourceManager.GetString("EndDay", resourceCulture);
            }
        }
        
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        internal static string Prefer {
            get {
                return ResourceManager.GetString("Prefer", resourceCulture);
            }
        }
        
        internal static string PowerPercent {
            get {
                return ResourceManager.GetString("PowerPercent", resourceCulture);
            }
        }
        
        internal static string EnabledScheduleDescription {
            get {
                return ResourceManager.GetString("EnabledScheduleDescription", resourceCulture);
            }
        }
        
        internal static string DisabledScheduleDescription {
            get {
                return ResourceManager.GetString("DisabledScheduleDescription", resourceCulture);
            }
        }
        
        internal static string DailyScheduleDescription {
            get {
                return ResourceManager.GetString("DailyScheduleDescription", resourceCulture);
            }
        }
        
        internal static string WeeklyScheduleDescription {
            get {
                return ResourceManager.GetString("WeeklyScheduleDescription", resourceCulture);
            }
        }
        
        internal static string ModuleTypeLed {
            get {
                return ResourceManager.GetString("ModuleTypeLed", resourceCulture);
            }
        }
        
        internal static string ModuleTypeUvLight {
            get {
                return ResourceManager.GetString("ModuleTypeUvLight", resourceCulture);
            }
        }
        
        internal static string ModuleTypeHumidifier {
            get {
                return ResourceManager.GetString("ModuleTypeHumidifier", resourceCulture);
            }
        }
        
        internal static string ModuleTypeWaterPump {
            get {
                return ResourceManager.GetString("ModuleTypeWaterPump", resourceCulture);
            }
        }
        
        internal static string ModuleTypeAirFlap {
            get {
                return ResourceManager.GetString("ModuleTypeAirFlap", resourceCulture);
            }
        }
    }
}
